version: '3.8'
services:
  nextgeneration-postgres:
    image: postgres:15-alpine
    container_name: nextgeneration-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nextgen_password
      POSTGRES_DB: nextgeneration
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
volumes:
  postgres_data:
