version: '3.8'

services:
  postgres_utf8_fixed:
    image: postgres:16-alpine
    container_name: nextgeneration_postgres_utf8_fixed
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SecurePostgresPassword2024!
      POSTGRES_DB: nextgeneration_utf8
      # SOLUTION EXPERT: locale=C pour éliminer conflits régionaux
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
      # Variables d'environnement POSIX pures
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      LC_COLLATE: C
      LC_CTYPE: C
    ports:
      - "5433:5432"  # Port différent pour éviter conflit
    volumes:
      - postgres_utf8_fixed_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nextgeneration_utf8"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    command: >
      postgres 
      -c log_statement=all
      -c log_destination=stderr
      -c logging_collector=off
      -c client_encoding=UTF8
      -c lc_messages=C
      -c default_text_search_config=pg_catalog.english

volumes:
  postgres_utf8_fixed_data:
    driver: local

networks:
  default:
    name: nextgeneration_utf8_fixed 