apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orchestrator.fullname" . }}-config
  labels:
    {{- include "orchestrator.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.config.environment | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  MAX_CONCURRENT_SESSIONS: {{ .Values.config.settings.max_concurrent_sessions | quote }}
  SESSION_TIMEOUT: {{ .Values.config.settings.session_timeout | quote }}
  REQUEST_TIMEOUT: {{ .Values.config.settings.request_timeout | quote }}
  LLM_TIMEOUT: {{ .Values.config.settings.llm_timeout | quote }} 