version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: adaptateur_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus_config.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/adaptateur_rules.yml:/etc/prometheus/adaptateur_rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: adaptateur_grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana_dashboard.json:/etc/grafana/provisioning/dashboards/adaptateur_v4.json
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: adaptateur_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  redis_exporter:
    image: oliver006/redis_exporter:latest
    container_name: adaptateur_redis_exporter
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis://redis:6379
    depends_on:
      - redis
    restart: unless-stopped 